### ISSUE TITLE
Unable to wget clamav executable

### ISSUE THREAD

**Issue by anweshadevgoel** [grofit/docker-clamav-windows#3]
Trying to downloading clamav executable using:
RUN powershell -Command "wget -Uri https://www.clamav.net/downloads/production/clamav-0.103.3-win-x64-portable.zip -OutFile clamav-win-x64-portable.zip -UseBasicParsing"

is returning 503 error
![image](https://user-images.githubusercontent.com/72664773/123670864-48cdc300-d85b-11eb-9e4f-65692ff79a80.png)

The same file can be downloaded successfully from browser. Am I missing someting?

**Comment by grofit** [comment]
Hey, were you missing something or is there an issue?

**Comment by anweshadevgoel** [comment]
I ended up using curl to download the file.
